# Generated by Django 4.1.3 on 2022-11-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_datetime', models.DateTimeField()),
                ('lat_recogida', models.IntegerField()),
                ('lon_recogida', models.IntegerField()),
                ('lat_destino', models.IntegerField()),
                ('lon_destino', models.IntegerField()),
                ('conductor', models.IntegerField()),
            ],
        ),
    ]
